version: "2"
services:
  rethinkdb:
    image: "rethinkdb"
    volumes:
      - ./data:/data
    ports:
      - "28015"
      - "8080:8080"
  app:
    image: "guigo2k/node-rethinkdb-api"
    environment:
      - DB_HOST=rethinkdb
      - DB_PORT=28015
      - DB_NAME=game
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
