apiVersion: v1
kind: Service
metadata:
  labels:
    app: app
  name: app
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: app

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: app
  name: app
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - image: guigo2k/node-rethinkdb-api
          imagePullPolicy: Always
          name: app
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: rdb-env
                  key: NODE_ENV
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: rdb-env
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: rdb-env
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: rdb-env
                  key: DB_NAME
          ports:
            - containerPort: 3000
