apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: rdb-proxy
  name: rdb-proxy
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: rdb-proxy
    spec:
      containers:
        -
          image: rethinkdb
          name: rdb-proxy
          command: ["rethinkdb"]
          args: ["proxy", "--bind", "all", "--join", "centos-test-rdb-k6qs", "--join", "centos-test-rdb-k8w9", "--join", "centos-test-rdb-p5k9"]
          ports:
            -
              containerPort: 28015

---

kind: Service
apiVersion: v1
metadata:
  name: rdb-proxy
spec:
  selector:
    app: rdb-proxy
  ports:
  - protocol: TCP
    port: 28015
    targetPort: 28015
